(local faith (require "faith"))

(faith.run ["vtx.test.ansi"
            "vtx.test.autocomplete"
            "vtx.test.checklist"
            "vtx.test.choose"
            "vtx.test.confirm"
            "vtx.test.date-picker"
            "vtx.test.dialog"
            "vtx.test.file-picker"
            "vtx.test.filter"
            "vtx.test.gauge"
            "vtx.test.gradient"
            "vtx.test.input"
            "vtx.test.key-help"
            "vtx.test.layout"
            "vtx.test.multi-form"
            "vtx.test.num-input"
            "vtx.test.pager"
            "vtx.test.password"
            "vtx.test.progress"
            "vtx.test.radio"
            "vtx.test.slider"
            "vtx.test.sparkline"
            "vtx.test.spin"
            "vtx.test.style"
            "vtx.test.table"
            "vtx.test.tabs"
            "vtx.test.theme"
            "vtx.test.tree"
            "vtx.test.util"
            "vtx.test.viewport"])
