(local faith (require "faith"))

(faith.run ["irx.test.ansi"
            "irx.test.autocomplete"
            "irx.test.checklist"
            "irx.test.choose"
            "irx.test.confirm"
            "irx.test.date-picker"
            "irx.test.dialog"
            "irx.test.file-picker"
            "irx.test.filter"
            "irx.test.gauge"
            "irx.test.gradient"
            "irx.test.input"
            "irx.test.key-help"
            "irx.test.layout"
            "irx.test.multi-form"
            "irx.test.num-input"
            "irx.test.pager"
            "irx.test.password"
            "irx.test.progress"
            "irx.test.radio"
            "irx.test.slider"
            "irx.test.sparkline"
            "irx.test.spin"
            "irx.test.style"
            "irx.test.table"
            "irx.test.tabs"
            "irx.test.theme"
            "irx.test.tree"
            "irx.test.util"
            "irx.test.viewport"])
